### ISSUE TITLE
MIM training while training object detection

### ISSUE THREAD

**Issue by bamps53** [hustvl/MIMDet#10]
Hi, thanks for sharing such a interesting work!
Have you tried to train decoder with reconstruction loss while training object detection part? I know there is a kind of information leakage by changing image patcher to conv one. But same thing can be said to current modeling(i.e. MIM is not useful with conv patchifier), but it seems working well and improving object detection performance.
So my question is, have you already tried and found that taking reconstruction loss actually degrade the benefit for object detection part?

Thanks in advance!

**Comment by Yuxin-CV** [comment]
Hi @bamps53 and thank you for your interest in our work.

We are trying a similar approach, and we will update in our revision as long as the recon objective is beneficial to detection performances.

**Comment by bamps53** [comment]
Thanks for the answer!
Good to know you're trying same idea, can't wait to see the results:)
It means currently it's not clear whether it's helpful or not, right?
I'll also try it in my project.

Thanks!
