### ISSUE TITLE
Hi, what is the writing method to the right of the equal sign in statement  ' img_size="${..encoder.img_size}" '

### ISSUE THREAD

**Issue by xiaoxiong007** [hustvl/MIMDet#12]
What does .. mean ?

**Comment by vealocia** [comment]
Hi, @xiaoxiong007 .
```${..encoder.img_size}``` is an expression of ```OmegaConf```, you can find a detailed documents [here](https://omegaconf.readthedocs.io/en). And in short, ```..``` indicates the parent node of current leaf node.

**Comment by xiaoxiong007** [comment]
Thank you, i get it!

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
