### ISSUE TITLE
How should I set the dataset's path??

### ISSUE THREAD

**Issue by ucasligang** [hustvl/MIMDet#18]
Hi, 
Excellent work! I want to ask a little question, how should I set the dataset's path? I search it through a few files, but I didn't find it.
Looking forward to your reply.

Sincerely,
Gang Li.

**Comment by Yuxin-CV** [comment]
Hi, @ucasligang, thank you for your interest in our work.

MIMDet is built upon D2,
- For built-in datasets (COCO, LVIS, etc.), please refer to https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html
- For custom datasets, please refer to https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
