### ISSUE TITLE
How to visualize results？

### ISSUE THREAD

**Issue by LowPower-Center** [hustvl/MIMDet#22]
I want to use the video stream as input and get the visualization results, I don't know if this model can modify the input interface to achieve the effect like detectron2/demo

**Comment by vealocia** [comment]
Hi, @LowPower-Center! Thanks for your interest in our work.
It seems detectron/demo script is not compatible with lazy config. You can refer [detectron/issues/3416](https://github.com/facebookresearch/detectron2/issues/3416) for more details and possible solution.

**Comment by Cococyh** [comment]
hi, @youngwanLEE. I use the related code and only change the config-file path(use this pro configs/mimdet_vit_base_mask_rcnn_fpn_sr_0p5_800_1333_4xdec_coco_3x.py),
then I got the same result as my input photo, It same like doing nothing with the predictor :(
