### ISSUE TITLE
problem about config of benchmark

### ISSUE THREAD

**Issue by UcanSee** [hustvl/MIMDet#5]
Thanks for sharing such a good work!
Now I want to use your codes to reproduce performance of mask-rcnn-benchmarking-ep50, but it seems that the config is not consistent with the paper. In paper, bs=64, lr=8.0e-5,  wd=0.1 but bs=16, lr=1.6e-4,  wd=0.2 in your config which is not consistent with the train log you released. Is there something I understand wrongly? Could you please provide an exact config?

**Comment by vealocia** [comment]
Hi, @UcanSee ! Thanks for your interest in our work.
We have already updated the configs of benchmarking models few hours ago, please check the newest [config files](https://github.com/hustvl/MIMDet/commit/ae681b4b7d8c2ebf04899791eebb2cf68d7aedeb).

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
