### ISSUE TITLE
Could you provide a model of 768 dimension output image features?

### ISSUE THREAD

**Issue by Pter61** [hustvl/MIMDet#6]
There are many works that require image embeddings that have the same dimensions as text embeddings (e.g. BERT-base(768 dim), BERT-large(1024 dim). However, I noticed that you only provided the model of 1024 dimensions; therefore, could you provide more models of 768 dimensions?

**Comment by Yuxin-CV** [comment]
> There are many works that require image embeddings that have the same dimensions as text embeddings (e.g. BERT-base(768 dim), BERT-large(1024 dim). However, I noticed that you only provided the model of 1024 dimensions; therefore, could you provide more models of 768 dimensions?

Hi.
The embedding dim of all the vit base models is 768.

**Comment by Pter61** [comment]
> > There are many works that require image embeddings that have the same dimensions as text embeddings (e.g. BERT-base(768 dim), BERT-large(1024 dim). However, I noticed that you only provided the model of 1024 dimensions; therefore, could you provide more models of 768 dimensions?
> 
> Hi. The embedding dim of all the vit base models is 768.

OK! Thank you!
