### ISSUE TITLE
Inf/NaN error happens during the training

### ISSUE THREAD

**Issue by junchen14** [hustvl/MIMDet#7]
File "MIMDet/detectron2/detectron2/modeling/proposal_gen
erator/proposal_utils.py", line 99, in find_top_rpn_proposals
    raise FloatingPointError(
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diver
ged.

Hi, firstly thanks for your work.
but while I train your model with the default configuration, I faced this problem

the default configuration is as the following:
'python lazyconfig_train_net.py --config-file configs/mimdet/mimdet_vit_base_mask_rcnn_fpn_mr_0p25_800_1333_4xdec_coco_3x.py --num-gpus 4 --num-machines 1 --master_addr 127.0.0.1 --master_port 9998  mae_checkpoint.path=mae_pretrain_vit_base.pth'

do you have any ideas why this happen?

**Comment by simonJJJ** [comment]
Please use the full MAE pretrained weight (not just encoder) as mentioned in https://github.com/hustvl/MIMDet#training.

**Comment by junchen14** [comment]
thanks for this quick response and clear pointer.

Will follow your correct instruction and re-run the model  again!

**Comment by Yuxin-CV** [comment]
Hi @junchen14, it looks like you are using 4xGPUs to training our model with sample ratio = 0.25.

We just updated [a new training config](https://github.com/hustvl/MIMDet/blob/main/configs/mimdet/mimdet_vit_base_mask_rcnn_fpn_sr_0p25_800_1333_4xdec_coco_3x_bs16.py) with a batch size of 16 instead of 64, which matches the result of our default settings.

You can try our new config :)

**Comment by junchen14** [comment]
thanks very much. I will give it a try

**Comment by mike-huangdj** [comment]
Hello, did you solve this problem? @junchen14 ，I'm having the same problem．
When my default configuration: "python lazyconfig_train_net.py --num-gpus 1 --config-file configs/mimdet/mimdet_vit_base_mask_rcnn_fpn_sr_0p5_800_ 1333_4xdec_coco_3x.py --num-machines 1".
Training has diverged.", "FloatingPointError: Predicted boxes or scores contain Inf/NaN.
I should follow the complete MAE pre-training weights provided by the  author@Yuxin-CV , but I am confused, I did not find the training weights for the decoder in question, where is this decoder? How should I place it?

**Comment by mike-huangdj** [comment]
When running: "python lazyconfig_train_net.py --num-gpus 1 --config-file configs/mimdet/mimdet_vit_base_mask_rcnn_fpn_sr_0p5_800_ 1333_4xdec_coco_ 3x.py --num-machines 1", appears:
![11](https://github.com/hustvl/MIMDet/assets/132533111/54235f8f-a1d5-4efa-9cee-057aefe91dde)
![22](https://github.com/hustvl/MIMDet/assets/132533111/d889741e-e8f3-4636-9b55-2a04d2c04a2a)
![33](https://github.com/hustvl/MIMDet/assets/132533111/a8004d01-9dda-4555-8cf5-c9026d18511c)

And I found the definition of encoder and decoder in "mimdet_vit_base_mask_rcnn_fpn_sr_0p5_800_ 1333_4xdec_coco_3x.py --num-machines 1", as shown in the figure:
![44](https://github.com/hustvl/MIMDet/assets/132533111/e87ae9d2-8a28-4dd6-ba66-ade08932d3fb)

For the encoder weights, modify them in common.py,
![55](https://github.com/hustvl/MIMDet/assets/132533111/a7843b00-204c-4dc1-9891-fcac424a9de3)

I look forward to your reply, if there is any disturbance, please bear with me, sincerely.
