### ISSUE TITLE
I want to do the downstream detection task based on your upstream pretraining model. Do you have a more detailed document

### ISSUE THREAD

**Issue by raychiu0202** [hustvl/MIMDet#8]

**Comment by Yuxin-CV** [comment]
MIMDet is based on Detectron2 v0.6, I suggest you refer to the official D2 doc for custom datasets: https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was (partially) addressed, as such I'm closing this. Feel free to ask if you have further questions.
