### ISSUE TITLE
AP performance is not consistent with training log?

### ISSUE THREAD

**Issue by ZHANGHeng19931123** [hustvl/MIMDet#9]
Hello, I find the "bbox/AP" score in the log (json file) is not the same with the AP listed in the table.
For example, in "mimdet_vit_base_mask_rcnn_fpn_sr_0p25_800_1333_4xdec_coco_3x.json" it reports 46.759384068659074 at the end of the file, while the AP is 49.9 in the table. Did I misunderstand something?

**Comment by Yuxin-CV** [comment]
Hi @ZHANGHeng19931123 and thanks for your interest in our work.

The results in the log are evaluated using a sample ratio = 0.25, while our MIMDet can benefit from larger sample ratio during inference. By default, we use sample ratio = 1 for evaluations, i.e., we don't drop any patch.

Also see Table 2 in our paper and https://github.com/hustvl/MIMDet#inference.

**Comment by ZHANGHeng19931123** [comment]
Thank you for your reply.
